imports:
    - { resource: services/* }

parameters:
    jwt_ttl: '+1 hour'
    jwt_algorithm: 'RS256'
    jwt_private_key: '%kernel.project_dir%/config/jwt/rsa_256'
    jwt_public_key: '%kernel.project_dir%/config/jwt/rsa_256.pub'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Command,Controller,Repository,Security,Service,Util,Kernel.php}'